# Keep RBAC enabled
global:
  rbac:
    create: true

# Prometheus configuration
prometheus:
  prometheusSpec:
    retention: 10d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: efs-sc
          accessModes: ["ReadWriteMany"] # Consistent with Grafana for EFS
          resources:
            requests:
              storage: 1Gi
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"
    nodeSelector:
      dedicated: monitoring
  ingress:
    enabled: false

# Alertmanager configuration
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: efs-sc
          accessModes: ["ReadWriteMany"] # Consistent with Grafana for EFS
          resources:
            requests:
              storage: 1Gi
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"
    nodeSelector:
      dedicated: monitoring
  ingress:
    enabled: false

# Grafana inside kube-prometheus-stack (disabled since you use standalone Grafana)
grafana:
  enabled: false