persistence:
  enabled: true
  type: pvc
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  size: 1Gi

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: monitor.mergeleaf.com
      paths:
        - path: /
          pathType: Prefix

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"

nodeSelector:
  dedicated: monitoring