persistence:
  enabled: true
  type: pvc
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  size: 1Gi

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"

nodeSelector:
  dedicated: monitoring