persistence:
  enabled: true
  type: pvc
  storageClassName: efs-sc
  accessModes:
    - ReadWriteOnce
  size: 1Gi

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - monitoring.mergeleaf.com
