apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http  # Added port name - required for ServiceMonitor
      port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.containerPort | default 8080 }}
