replicaCount: 1

image:
  repository: 262235594053.dkr.ecr.us-east-2.amazonaws.com/demo-app
  tag: 1.0.0
  pullPolicy: Always

service:
  containerPort: 8080
  type: ClusterIP
  port: 8080

configMapName: demo-app-config

# Spring Boot properties
spring:
  applicationName: demo-app

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"
