replicaCount: 1

image:
  repository: 049229311885.dkr.ecr.eu-north-1.amazonaws.com/fb
  tag: 1.0.0
  pullPolicy: Always

service:
  containerPort: 8080
  type: LoadBalancer
  port: 8080

configMapName: demo-app-config

# Spring Boot properties
spring:
  applicationName: demo-app
